#!/usr/bin/env node
/**
 * build-content.js — Combines individual JSON content files into
 * a single js/content-data.js that can be loaded via <script> tag.
 *
 * Run this after adding or editing any content JSON file:
 *   node build-content.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const WRITINGS_DIR = path.join(ROOT, 'content', 'writings');
const THINKING_DIR = path.join(ROOT, 'content', 'thinking');
const OUTPUT = path.join(ROOT, 'js', 'content-data.js');

function readJsonDir(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      const raw = fs.readFileSync(path.join(dir, f), 'utf8');
      return JSON.parse(raw);
    });
}

const writings = readJsonDir(WRITINGS_DIR);
// Sort writings by date descending
writings.sort((a, b) => (b.date || '').localeCompare(a.date || ''));

const thinking = readJsonDir(THINKING_DIR);
// Featured items first
thinking.sort((a, b) => (b.featured ? 1 : 0) - (a.featured ? 1 : 0));

const output = `/* Auto-generated by build-content.js — do not edit manually */
var ARTICLES = ${JSON.stringify(writings, null, 2)};

var THINKING = ${JSON.stringify(thinking, null, 2)};
`;

fs.writeFileSync(OUTPUT, output);
console.log(`✓ Built ${OUTPUT}`);
console.log(`  ${writings.length} writings, ${thinking.length} thinking items`);
